### ISSUE TITLE
Set-BlueLight - set the color temperature without affecting other settings

### ISSUE THREAD

**Issue by tiborbaksa** [jaapbrasser/SharedScripts#14]
There is a single byte in the Data value that controls the color temperature, therefore there's no need to overwrite the entire value.

If you look at the data of the `NoShift`, `MinimumShift`, `MediumShift`, `LargeShift` and `MaximumShift` byte arrays, you will find a byte sequence of `207, 40, X, Y, 202, 50, 14`. I was not able to determine what `X` is, but `Y` corresponds to the color temperature. It has a value between `0x12` and  `0x65` on my system (Creators update, build 1703). The lower value corresponds to 1200K based on [this insider build announcement](https://blogs.windows.com/windowsexperience/2017/02/01/announcing-windows-10-insider-preview-build-15025-pc/), and the upper value corresponds to 6500K based on f.lux's Daylight setting.

Assuming a linear scale, you can calculate the byte value for a desired temperature using [this formula](http://www.wolframalpha.com/input/?i=((x+-+1800)+*+(0x65+-+0x12)+%2F+(6500+-+1800))+%2B+0x12+where+x+%3D+3400) (I used 3400K as an example).

**Comment by tiborbaksa** [comment]
Please disregard my previous comment, I've got new information.

The value is actually a [ZigZag-encoded 16 bit integer](https://developers.google.com/protocol-buffers/docs/encoding#signed-integers), and the binary structure of the Data value is a `Windows.Data.BlueLightReduction.Settings` data structure serialized to [Microsoft Bond](https://github.com/Microsoft/bond) compactbinary. `X` essentially stores the lower 6 bits of the value:
```
X=[1]lllllll
Y=[0]hhhhhhh
ColorTemperature=ZigZagDecode(hhhhhhhlllllll)
```

If the original value is positive (which is the case here), then ZigZagDecode is simply a right shift (or division by 2).

Using this encoding the upper bound is 6500 and the lower bound is 1200 of the color temperature.

Thanks @snq- for the comprehensive analysis.

**Comment by jaapbrasser** [comment]
Hello Tiborbaksa,

My apologies for the slow response, this is very useful information. Although I am a bit unfamiliar with either ZigZag encoding and the Microsoft Bond framework. I will dive deeper into this and implement this into my code once I figure out how to convert your description to PowerShell code.

Thanks again for your contribution!


Regards,

Jaap Brasser

**Comment by jaapbrasser** [comment]
This functionality has been updated in later Windows 10 builds, we cannot resolve this with the solution presented. I presume I will have to rework this module.

**Comment by Coldblackice** [comment]
> This functionality has been updated in later Windows 10 builds, we cannot resolve this with the solution presented. I presume I will have to completely rework this function.

Any hope of an update on this? Or has it been too complexified for unraveling?
