### ISSUE TITLE
Get-LoggedOnUser - Add ComputerName hardcoding and output sorting.

### ISSUE THREAD

**Issue by SunsparcSolaris** [jaapbrasser/SharedScripts#19]
If possible in the current script, hash out in script commenting.

Ability to hardcode the remote computers/servers into the code rather than piping them in.

Sorting the output by username, ID, or computername.

**Comment by jaapbrasser** [comment]
Hello SunsparcSolaris,

I suggest you write another script or function that calls this script with the set values and sorting options you are looking for, this can be a simple oneline script that looks something like this:
.\Get-LoggedOnUser.ps1 -ComputerName server1,server2,server3 | Sort-Object -Property ComputerName

You could by changing the script as well, for adding the computer names you could change line 36 and enter an array of computer names there as such:
`[string[]]$ComputerName = @('server1','server2','server3')`


Let me know if that helps!
