### ISSUE TITLE
Get-RemoteProgram - Sorting?

### ISSUE THREAD

**Issue by mr-aleks** [jaapbrasser/SharedScripts#25]
Hello, I liked your script. Can you add sorting to the output of the script?

**Comment by tehfonz** [comment]
My recommendation would be
`$Programs = Get-RemoteProgram | Sort-Object ComputerName `
or
`$Programs = Get-RemoteProgram | Sort-Object ProgramName`

**Comment by mr-aleks** [comment]
Thanks, this works, I did not know what the properties are called

**Comment by jaapbrasser** [comment]
@tehfonz Thanks for answering this one!
