### ISSUE TITLE
Terms of Use

### ISSUE THREAD

**Issue by AlexeiStarchenko** [jaapbrasser/SharedScripts#27]
Jaap,

I was talking to GitHub support about the terms of use of the scripts that you published (I am particularly interested in the one called deleteold.ps1) and they suggested I create an issue and ask you this question.

Since I did not find any information on licensing or terms of use that you specify this is the assumption (according to the tech support) that I have to make: "have no permission from the creators of the software to use, modify, or share the software". 

So my question is: Can I "use" your script to create a similar script of my own (and frankly I am not sure if I will be able to avoid using copy and paste :) )? Or. Can I "use" your script directly in my production environment to clean up the scans folder? Or. Can I only "use" it to educate myself on how PowerShell scripting works?

Thank you.

Alex Starchenko.

**Comment by jaapbrasser** [comment]
Hello Alexei, thanks for reaching out, I will add proper licensing for this repository!

**Comment by jaapbrasser** [comment]
Updated my repository with MIT licensing, so you are free to use the scripts in this repository according to the MIT license which will allow you to modify and deploy the scripts as you'd like!

If you build something cool or come up with a modification feel free to either do a PR here or drop me a message on twitter: [@jaap_brasser](https://www.twitter.com/jaap_brasser)
