### ISSUE TITLE
Set-BlueLight not working on Update 1903

### ISSUE THREAD

**Issue by prayzzz** [jaapbrasser/SharedScripts#30]
Hi,

I just upgraded to Windows 10 1903 and Set-BlueLight stopped working. 
e.g.
```sh
Set-BlueLight -EnableBlueLight
```
Runs without any effect. No error message is shown.

**Comment by jaapbrasser** [comment]
Hello @prayzzz, thanks for reporting this. I will take a look at this and find out the correct method of configuring this on the latest Windows 10 version.

**Comment by jaapbrasser** [comment]
Hello @prayzzz,

I have just confirmed Set-BlueLight does indeed not respond as expected. The last version of Windows 10 it works on is 1809.

I will update the script so it detects the version of Windows 10 and sets the blue light (night light) mode accordingly.

**Comment by prayzzz** [comment]
@jaapbrasser Thanks for looking into this. 👍

**Comment by jaapbrasser** [comment]
@prayzzz I have located the new registry keys, but I noticed some strange behavior when setting it using the script. So far I have been unable to enable or disable any settings through the registry, as it does not appear to get picked up. I will research this further and let you know what I find.

**Comment by jaapbrasser** [comment]
Closing issue, did not find a fix for this problem as the registry keys no longer function.

**Comment by bpsib** [comment]
An issue for something unfixed should NOT be closed. I really need a way of toggling Night Light from the command line. Even if it means someone reverse engineers the Settings app to get the code to set it on and off. I would even happily award whoever solves this problem.
