### ISSUE TITLE
Add Lastlogondate option to Get-OrphanHomeFolder

### ISSUE THREAD

**Issue by jaapbrasser** [jaapbrasser/SharedScripts#37]
Attempt to discover the last logon date for this and add this as an optional property

**Comment by lkrzyczkowski** [comment]
Great option

**Comment by jaapbrasser** [comment]
Hey @lkrzyczkowski,

I've created a pull request, let me know if this matches the output you are expectation. Since these are orphaned folders, I'll check for the LastWriteTime on all of the files in the root folder and determine the LastLogon based on that.

Let me know if that approximation works for you!
